# Generated by Django 5.2.1 on 2025-05-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='usuario',
            new_name='user',
        ),
    ]
