# Generated by Django 5.2.1 on 2025-05-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('AP', 'Apartamento'), ('CA', 'Casa')], max_length=2)),
                ('quartos', models.PositiveSmallIntegerField()),
                ('descricao', models.TextField()),
                ('capa', models.ImageField(upload_to='imoveis/')),
                ('data_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('pode_publicar', 'Pode publicar imóvel')],
            },
        ),
    ]
