# Generated by Django 5.2.1 on 2025-06-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_interesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='capa',
        ),
        migrations.AddField(
            model_name='imovel',
            name='capa_url',
            field=models.URLField(default='https://via.placeholder.com/800x600/4f46e5/ffffff?text=Imóvel', help_text='Cole aqui a URL da imagem do imóvel (ex: https://exemplo.com/foto.jpg)', verbose_name='URL da Imagem'),
        ),
    ]
