# Generated by Django 5.2.1 on 2025-07-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_imovel_capa_imovel_capa_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('PR', 'Pronto'), ('EO', 'Em Obra')], default='PR', max_length=2),
        ),
    ]
